// Code generated by protoc-gen-go. DO NOT EDIT.
// source: github.com/DOSNetwork/core/share/dkg/pedersen/dkg.proto

package dkg

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import pedersen "github.com/DOSNetwork/core/share/vss/pedersen"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type PublicKey struct {
	SessionId            string              `protobuf:"bytes,1,opt,name=sessionId,proto3" json:"sessionId,omitempty"`
	Index                uint32              `protobuf:"varint,2,opt,name=index,proto3" json:"index,omitempty"`
	Publickey            *pedersen.PublicKey `protobuf:"bytes,3,opt,name=publickey,proto3" json:"publickey,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *PublicKey) Reset()         { *m = PublicKey{} }
func (m *PublicKey) String() string { return proto.CompactTextString(m) }
func (*PublicKey) ProtoMessage()    {}
func (*PublicKey) Descriptor() ([]byte, []int) {
	return fileDescriptor_b7eac839653a0a37, []int{0}
}
func (m *PublicKey) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PublicKey.Unmarshal(m, b)
}
func (m *PublicKey) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PublicKey.Marshal(b, m, deterministic)
}
func (dst *PublicKey) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PublicKey.Merge(dst, src)
}
func (m *PublicKey) XXX_Size() int {
	return xxx_messageInfo_PublicKey.Size(m)
}
func (m *PublicKey) XXX_DiscardUnknown() {
	xxx_messageInfo_PublicKey.DiscardUnknown(m)
}

var xxx_messageInfo_PublicKey proto.InternalMessageInfo

func (m *PublicKey) GetSessionId() string {
	if m != nil {
		return m.SessionId
	}
	return ""
}

func (m *PublicKey) GetIndex() uint32 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *PublicKey) GetPublickey() *pedersen.PublicKey {
	if m != nil {
		return m.Publickey
	}
	return nil
}

type Deal struct {
	SessionId            string                  `protobuf:"bytes,1,opt,name=sessionId,proto3" json:"sessionId,omitempty"`
	Index                uint32                  `protobuf:"varint,2,opt,name=index,proto3" json:"index,omitempty"`
	Deal                 *pedersen.EncryptedDeal `protobuf:"bytes,3,opt,name=deal,proto3" json:"deal,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *Deal) Reset()         { *m = Deal{} }
func (m *Deal) String() string { return proto.CompactTextString(m) }
func (*Deal) ProtoMessage()    {}
func (*Deal) Descriptor() ([]byte, []int) {
	return fileDescriptor_b7eac839653a0a37, []int{1}
}
func (m *Deal) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Deal.Unmarshal(m, b)
}
func (m *Deal) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Deal.Marshal(b, m, deterministic)
}
func (dst *Deal) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Deal.Merge(dst, src)
}
func (m *Deal) XXX_Size() int {
	return xxx_messageInfo_Deal.Size(m)
}
func (m *Deal) XXX_DiscardUnknown() {
	xxx_messageInfo_Deal.DiscardUnknown(m)
}

var xxx_messageInfo_Deal proto.InternalMessageInfo

func (m *Deal) GetSessionId() string {
	if m != nil {
		return m.SessionId
	}
	return ""
}

func (m *Deal) GetIndex() uint32 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *Deal) GetDeal() *pedersen.EncryptedDeal {
	if m != nil {
		return m.Deal
	}
	return nil
}

type Response struct {
	SessionId            string             `protobuf:"bytes,1,opt,name=sessionId,proto3" json:"sessionId,omitempty"`
	Index                uint32             `protobuf:"varint,2,opt,name=index,proto3" json:"index,omitempty"`
	Response             *pedersen.Response `protobuf:"bytes,3,opt,name=response,proto3" json:"response,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_b7eac839653a0a37, []int{2}
}
func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (dst *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(dst, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetSessionId() string {
	if m != nil {
		return m.SessionId
	}
	return ""
}

func (m *Response) GetIndex() uint32 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *Response) GetResponse() *pedersen.Response {
	if m != nil {
		return m.Response
	}
	return nil
}

type Responses struct {
	SessionId            string      `protobuf:"bytes,1,opt,name=sessionId,proto3" json:"sessionId,omitempty"`
	Response             []*Response `protobuf:"bytes,2,rep,name=response,proto3" json:"response,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Responses) Reset()         { *m = Responses{} }
func (m *Responses) String() string { return proto.CompactTextString(m) }
func (*Responses) ProtoMessage()    {}
func (*Responses) Descriptor() ([]byte, []int) {
	return fileDescriptor_b7eac839653a0a37, []int{3}
}
func (m *Responses) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Responses.Unmarshal(m, b)
}
func (m *Responses) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Responses.Marshal(b, m, deterministic)
}
func (dst *Responses) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Responses.Merge(dst, src)
}
func (m *Responses) XXX_Size() int {
	return xxx_messageInfo_Responses.Size(m)
}
func (m *Responses) XXX_DiscardUnknown() {
	xxx_messageInfo_Responses.DiscardUnknown(m)
}

var xxx_messageInfo_Responses proto.InternalMessageInfo

func (m *Responses) GetSessionId() string {
	if m != nil {
		return m.SessionId
	}
	return ""
}

func (m *Responses) GetResponse() []*Response {
	if m != nil {
		return m.Response
	}
	return nil
}

func init() {
	proto.RegisterType((*PublicKey)(nil), "dkg.PublicKey")
	proto.RegisterType((*Deal)(nil), "dkg.Deal")
	proto.RegisterType((*Response)(nil), "dkg.Response")
	proto.RegisterType((*Responses)(nil), "dkg.Responses")
}

func init() {
	proto.RegisterFile("github.com/DOSNetwork/core/share/dkg/pedersen/dkg.proto", fileDescriptor_b7eac839653a0a37)
}

var fileDescriptor_b7eac839653a0a37 = []byte{
	// 262 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x91, 0xcd, 0x4a, 0xc3, 0x40,
	0x14, 0x85, 0x49, 0x5b, 0xa5, 0xb9, 0x52, 0x17, 0x83, 0x8b, 0x20, 0x2e, 0x42, 0x16, 0x12, 0x41,
	0x32, 0xa0, 0x0b, 0x5f, 0xa0, 0x2e, 0x44, 0x50, 0x19, 0x7d, 0x81, 0x24, 0x73, 0x49, 0x87, 0xa4,
	0x33, 0xc3, 0xdc, 0xb4, 0x9a, 0xb7, 0x97, 0x4c, 0xd3, 0x46, 0x70, 0x51, 0xe8, 0xf2, 0xfe, 0x9c,
	0xef, 0x5b, 0x1c, 0x78, 0xaa, 0x54, 0xbb, 0xda, 0x14, 0x59, 0x69, 0xd6, 0x7c, 0xf9, 0xfe, 0xf9,
	0x86, 0xed, 0xb7, 0x71, 0x35, 0x2f, 0x8d, 0x43, 0x4e, 0xab, 0xdc, 0x21, 0x97, 0x75, 0xc5, 0x2d,
	0x4a, 0x74, 0x84, 0xba, 0x1f, 0x32, 0xeb, 0x4c, 0x6b, 0xd8, 0x54, 0xd6, 0xd5, 0xf5, 0xf1, 0xf4,
	0x96, 0x68, 0x4c, 0x6f, 0x89, 0x76, 0xe9, 0x64, 0x0d, 0xe1, 0xc7, 0xa6, 0x68, 0x54, 0xf9, 0x8a,
	0x1d, 0xbb, 0x81, 0x90, 0x90, 0x48, 0x19, 0xfd, 0x22, 0xa3, 0x20, 0x0e, 0xd2, 0x50, 0x8c, 0x0b,
	0x76, 0x05, 0x67, 0x4a, 0x4b, 0xfc, 0x89, 0x26, 0x71, 0x90, 0x2e, 0xc4, 0x6e, 0x60, 0xf7, 0x10,
	0x5a, 0x0f, 0xa8, 0xb1, 0x8b, 0xa6, 0x71, 0x90, 0x5e, 0x3c, 0x5c, 0x66, 0x3d, 0xff, 0x80, 0x15,
	0xe3, 0x43, 0x52, 0xc0, 0x6c, 0x89, 0x79, 0x73, 0x92, 0xe9, 0x16, 0x66, 0x12, 0xf3, 0x66, 0x90,
	0x30, 0x2f, 0x79, 0xd6, 0xa5, 0xeb, 0x6c, 0x8b, 0xb2, 0xa7, 0x0a, 0x7f, 0x4f, 0x14, 0xcc, 0x05,
	0x92, 0x35, 0x9a, 0xf0, 0x24, 0xcf, 0x1d, 0xcc, 0xdd, 0x90, 0x1f, 0x5c, 0x0b, 0xef, 0xda, 0x43,
	0xc5, 0xe1, 0x9c, 0x7c, 0x41, 0xb8, 0xdf, 0xd2, 0x11, 0xd7, 0x5f, 0xea, 0x24, 0x9e, 0x7a, 0x6a,
	0x5f, 0xe2, 0x7f, 0x6a, 0x71, 0xee, 0xab, 0x79, 0xfc, 0x0d, 0x00, 0x00, 0xff, 0xff, 0xc0, 0x11,
	0xb3, 0x0d, 0x13, 0x02, 0x00, 0x00,
}
