FROM alpine:3.6 as alpine
RUN apk add -U --no-cache ca-certificates

FROM golang:1.13
WORKDIR /go/src/github.com/DOSNetwork/core
COPY . .
COPY --from=alpine /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/
