version: '3'
services:
 bootstrap:
   image: dhtnode
   deploy:
     replicas: 1
   environment:
     - NODEROLE=boot
     - DHTSIZE=5
 dhtnode:
   image: dhtnode
   depends_on:
     - bootstrap
   deploy:
     replicas: 3
   environment:
     - BOOTSTRAPIP=bootstrap:44460
