version: '3'
services:
 bootstrap:
   image: peertalk
   deploy:
     replicas: 1
   environment:
     - ROLE=bootstrap
     - PEERNUM=500
 peernode:
   image: peertalk
   depends_on:
     - bootstrap
   deploy:
     replicas: 500
   environment:
     - ROLE=testNode
     - BOOTSTRAPIP=bootstrap:44460