version: '3'
services:
 bootstrap:
   image: peertalk
   deploy:
     replicas: 1
   environment:
     - ROLE=bootstrap
     - PEERNUM=3
     - GROUPSIZE=3
 peernode:
   image: peertalk
   depends_on:
     - bootstrap
   deploy:
     replicas: 3
   environment:
     - ROLE=testNode
     - BOOTSTRAPIP=bootstrap:44460