// Code generated by protoc-gen-go. DO NOT EDIT.
// source: msg.proto

package msg

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type EncryptedDeal struct {
	DHKey                []byte   `protobuf:"bytes,1,opt,name=DHKey,json=dHKey,proto3" json:"DHKey,omitempty"`
	Signature            []byte   `protobuf:"bytes,2,opt,name=Signature,json=signature,proto3" json:"Signature,omitempty"`
	Nonce                []byte   `protobuf:"bytes,3,opt,name=Nonce,json=nonce,proto3" json:"Nonce,omitempty"`
	Cipher               []byte   `protobuf:"bytes,4,opt,name=Cipher,json=cipher,proto3" json:"Cipher,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EncryptedDeal) Reset()         { *m = EncryptedDeal{} }
func (m *EncryptedDeal) String() string { return proto.CompactTextString(m) }
func (*EncryptedDeal) ProtoMessage()    {}
func (*EncryptedDeal) Descriptor() ([]byte, []int) {
	return fileDescriptor_msg_6def996f3c344555, []int{0}
}
func (m *EncryptedDeal) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EncryptedDeal.Unmarshal(m, b)
}
func (m *EncryptedDeal) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EncryptedDeal.Marshal(b, m, deterministic)
}
func (dst *EncryptedDeal) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EncryptedDeal.Merge(dst, src)
}
func (m *EncryptedDeal) XXX_Size() int {
	return xxx_messageInfo_EncryptedDeal.Size(m)
}
func (m *EncryptedDeal) XXX_DiscardUnknown() {
	xxx_messageInfo_EncryptedDeal.DiscardUnknown(m)
}

var xxx_messageInfo_EncryptedDeal proto.InternalMessageInfo

func (m *EncryptedDeal) GetDHKey() []byte {
	if m != nil {
		return m.DHKey
	}
	return nil
}

func (m *EncryptedDeal) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

func (m *EncryptedDeal) GetNonce() []byte {
	if m != nil {
		return m.Nonce
	}
	return nil
}

func (m *EncryptedDeal) GetCipher() []byte {
	if m != nil {
		return m.Cipher
	}
	return nil
}

type Response struct {
	SessionID            []byte   `protobuf:"bytes,1,opt,name=SessionID,json=sessionID,proto3" json:"SessionID,omitempty"`
	Index                uint32   `protobuf:"varint,2,opt,name=Index,json=index,proto3" json:"Index,omitempty"`
	Status               bool     `protobuf:"varint,3,opt,name=Status,json=status,proto3" json:"Status,omitempty"`
	Signature            []byte   `protobuf:"bytes,4,opt,name=Signature,json=signature,proto3" json:"Signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_msg_6def996f3c344555, []int{1}
}
func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (dst *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(dst, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetSessionID() []byte {
	if m != nil {
		return m.SessionID
	}
	return nil
}

func (m *Response) GetIndex() uint32 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *Response) GetStatus() bool {
	if m != nil {
		return m.Status
	}
	return false
}

func (m *Response) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

type Justification struct {
	SessionID            []byte   `protobuf:"bytes,1,opt,name=SessionID,json=sessionID,proto3" json:"SessionID,omitempty"`
	Index                uint32   `protobuf:"varint,2,opt,name=Index,json=index,proto3" json:"Index,omitempty"`
	Deal                 []byte   `protobuf:"bytes,3,opt,name=Deal,json=deal,proto3" json:"Deal,omitempty"`
	Signature            []byte   `protobuf:"bytes,4,opt,name=Signature,json=signature,proto3" json:"Signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Justification) Reset()         { *m = Justification{} }
func (m *Justification) String() string { return proto.CompactTextString(m) }
func (*Justification) ProtoMessage()    {}
func (*Justification) Descriptor() ([]byte, []int) {
	return fileDescriptor_msg_6def996f3c344555, []int{2}
}
func (m *Justification) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Justification.Unmarshal(m, b)
}
func (m *Justification) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Justification.Marshal(b, m, deterministic)
}
func (dst *Justification) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Justification.Merge(dst, src)
}
func (m *Justification) XXX_Size() int {
	return xxx_messageInfo_Justification.Size(m)
}
func (m *Justification) XXX_DiscardUnknown() {
	xxx_messageInfo_Justification.DiscardUnknown(m)
}

var xxx_messageInfo_Justification proto.InternalMessageInfo

func (m *Justification) GetSessionID() []byte {
	if m != nil {
		return m.SessionID
	}
	return nil
}

func (m *Justification) GetIndex() uint32 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *Justification) GetDeal() []byte {
	if m != nil {
		return m.Deal
	}
	return nil
}

func (m *Justification) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

type PublicKey struct {
	PublicKey            []byte   `protobuf:"bytes,1,opt,name=PublicKey,json=publicKey,proto3" json:"PublicKey,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PublicKey) Reset()         { *m = PublicKey{} }
func (m *PublicKey) String() string { return proto.CompactTextString(m) }
func (*PublicKey) ProtoMessage()    {}
func (*PublicKey) Descriptor() ([]byte, []int) {
	return fileDescriptor_msg_6def996f3c344555, []int{3}
}
func (m *PublicKey) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PublicKey.Unmarshal(m, b)
}
func (m *PublicKey) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PublicKey.Marshal(b, m, deterministic)
}
func (dst *PublicKey) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PublicKey.Merge(dst, src)
}
func (m *PublicKey) XXX_Size() int {
	return xxx_messageInfo_PublicKey.Size(m)
}
func (m *PublicKey) XXX_DiscardUnknown() {
	xxx_messageInfo_PublicKey.DiscardUnknown(m)
}

var xxx_messageInfo_PublicKey proto.InternalMessageInfo

func (m *PublicKey) GetPublicKey() []byte {
	if m != nil {
		return m.PublicKey
	}
	return nil
}

type PublicKeys struct {
	PublicKey            [][]byte `protobuf:"bytes,1,rep,name=PublicKey,json=publicKey,proto3" json:"PublicKey,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PublicKeys) Reset()         { *m = PublicKeys{} }
func (m *PublicKeys) String() string { return proto.CompactTextString(m) }
func (*PublicKeys) ProtoMessage()    {}
func (*PublicKeys) Descriptor() ([]byte, []int) {
	return fileDescriptor_msg_6def996f3c344555, []int{4}
}
func (m *PublicKeys) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PublicKeys.Unmarshal(m, b)
}
func (m *PublicKeys) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PublicKeys.Marshal(b, m, deterministic)
}
func (dst *PublicKeys) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PublicKeys.Merge(dst, src)
}
func (m *PublicKeys) XXX_Size() int {
	return xxx_messageInfo_PublicKeys.Size(m)
}
func (m *PublicKeys) XXX_DiscardUnknown() {
	xxx_messageInfo_PublicKeys.DiscardUnknown(m)
}

var xxx_messageInfo_PublicKeys proto.InternalMessageInfo

func (m *PublicKeys) GetPublicKey() [][]byte {
	if m != nil {
		return m.PublicKey
	}
	return nil
}

func init() {
	proto.RegisterType((*EncryptedDeal)(nil), "msg.EncryptedDeal")
	proto.RegisterType((*Response)(nil), "msg.Response")
	proto.RegisterType((*Justification)(nil), "msg.Justification")
	proto.RegisterType((*PublicKey)(nil), "msg.PublicKey")
	proto.RegisterType((*PublicKeys)(nil), "msg.PublicKeys")
}

func init() { proto.RegisterFile("msg.proto", fileDescriptor_msg_6def996f3c344555) }

var fileDescriptor_msg_6def996f3c344555 = []byte{
	// 254 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x91, 0xcf, 0x4a, 0x03, 0x31,
	0x10, 0xc6, 0xa9, 0xfb, 0x87, 0x66, 0x70, 0x2f, 0x41, 0x64, 0x0f, 0x1e, 0x64, 0x4f, 0xea, 0xc1,
	0x8b, 0x8f, 0xe0, 0x0a, 0x56, 0x41, 0x64, 0xfb, 0x04, 0xdb, 0xec, 0xb8, 0x06, 0xda, 0x24, 0xee,
	0x24, 0x60, 0xdf, 0x5e, 0x32, 0x6e, 0x0a, 0xed, 0xc1, 0x83, 0xc7, 0xef, 0x9b, 0x3f, 0xbf, 0xc9,
	0x17, 0x10, 0x3b, 0x1a, 0xef, 0xdd, 0x64, 0xbd, 0x95, 0xd9, 0x8e, 0xc6, 0xe6, 0x0b, 0xaa, 0x27,
	0xa3, 0xa6, 0xbd, 0xf3, 0x38, 0xb4, 0xd8, 0x6f, 0xe5, 0x05, 0x14, 0xed, 0xf3, 0x2b, 0xee, 0xeb,
	0xc5, 0xf5, 0xe2, 0xe6, 0xbc, 0x2b, 0x86, 0x28, 0xe4, 0x15, 0x88, 0xb5, 0x1e, 0x4d, 0xef, 0xc3,
	0x84, 0xf5, 0x19, 0x57, 0x04, 0x25, 0x23, 0xce, 0xbc, 0x59, 0xa3, 0xb0, 0xce, 0x7e, 0x67, 0x4c,
	0x14, 0xf2, 0x12, 0xca, 0x47, 0xed, 0x3e, 0x71, 0xaa, 0x73, 0xb6, 0x4b, 0xc5, 0xaa, 0xf1, 0xb0,
	0xec, 0x90, 0x9c, 0x35, 0x84, 0xbc, 0x17, 0x89, 0xb4, 0x35, 0xab, 0x76, 0x26, 0x0a, 0x4a, 0x46,
	0xdc, 0xbb, 0x32, 0x03, 0x7e, 0x33, 0xb1, 0xea, 0x0a, 0x1d, 0x45, 0xdc, 0xbb, 0xf6, 0xbd, 0x0f,
	0xc4, 0xb8, 0x65, 0x57, 0x12, 0xab, 0xe3, 0x1b, 0xf3, 0x93, 0x1b, 0x9b, 0x00, 0xd5, 0x4b, 0x20,
	0xaf, 0x3f, 0xb4, 0xea, 0xbd, 0xb6, 0xe6, 0x5f, 0x68, 0x09, 0x79, 0x0c, 0x69, 0x7e, 0x67, 0x3e,
	0xc4, 0xc0, 0xfe, 0xc6, 0xde, 0x82, 0x78, 0x0f, 0x9b, 0xad, 0x56, 0x73, 0x8a, 0x07, 0x91, 0x90,
	0x2e, 0x19, 0xcd, 0x1d, 0xc0, 0xa1, 0x4a, 0xa7, 0xbd, 0xd9, 0x51, 0xef, 0xa6, 0xe4, 0x2f, 0x7c,
	0xf8, 0x09, 0x00, 0x00, 0xff, 0xff, 0x72, 0xde, 0x1c, 0x77, 0xcf, 0x01, 0x00, 0x00,
}
