// Code generated by protoc-gen-go. DO NOT EDIT.
// source: msg.proto

package internal

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type EncryptedDeal struct {
	DHKey                []byte   `protobuf:"bytes,1,opt,name=DHKey,proto3" json:"DHKey,omitempty"`
	Signature            []byte   `protobuf:"bytes,2,opt,name=Signature,proto3" json:"Signature,omitempty"`
	Nonce                []byte   `protobuf:"bytes,3,opt,name=Nonce,proto3" json:"Nonce,omitempty"`
	Cipher               []byte   `protobuf:"bytes,4,opt,name=Cipher,proto3" json:"Cipher,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EncryptedDeal) Reset()         { *m = EncryptedDeal{} }
func (m *EncryptedDeal) String() string { return proto.CompactTextString(m) }
func (*EncryptedDeal) ProtoMessage()    {}
func (*EncryptedDeal) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{0}
}
func (m *EncryptedDeal) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EncryptedDeal.Unmarshal(m, b)
}
func (m *EncryptedDeal) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EncryptedDeal.Marshal(b, m, deterministic)
}
func (dst *EncryptedDeal) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EncryptedDeal.Merge(dst, src)
}
func (m *EncryptedDeal) XXX_Size() int {
	return xxx_messageInfo_EncryptedDeal.Size(m)
}
func (m *EncryptedDeal) XXX_DiscardUnknown() {
	xxx_messageInfo_EncryptedDeal.DiscardUnknown(m)
}

var xxx_messageInfo_EncryptedDeal proto.InternalMessageInfo

func (m *EncryptedDeal) GetDHKey() []byte {
	if m != nil {
		return m.DHKey
	}
	return nil
}

func (m *EncryptedDeal) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

func (m *EncryptedDeal) GetNonce() []byte {
	if m != nil {
		return m.Nonce
	}
	return nil
}

func (m *EncryptedDeal) GetCipher() []byte {
	if m != nil {
		return m.Cipher
	}
	return nil
}

type EncryptedDeals struct {
	Deals                []*EncryptedDeal `protobuf:"bytes,1,rep,name=Deals,proto3" json:"Deals,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *EncryptedDeals) Reset()         { *m = EncryptedDeals{} }
func (m *EncryptedDeals) String() string { return proto.CompactTextString(m) }
func (*EncryptedDeals) ProtoMessage()    {}
func (*EncryptedDeals) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{1}
}
func (m *EncryptedDeals) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EncryptedDeals.Unmarshal(m, b)
}
func (m *EncryptedDeals) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EncryptedDeals.Marshal(b, m, deterministic)
}
func (dst *EncryptedDeals) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EncryptedDeals.Merge(dst, src)
}
func (m *EncryptedDeals) XXX_Size() int {
	return xxx_messageInfo_EncryptedDeals.Size(m)
}
func (m *EncryptedDeals) XXX_DiscardUnknown() {
	xxx_messageInfo_EncryptedDeals.DiscardUnknown(m)
}

var xxx_messageInfo_EncryptedDeals proto.InternalMessageInfo

func (m *EncryptedDeals) GetDeals() []*EncryptedDeal {
	if m != nil {
		return m.Deals
	}
	return nil
}

type Response struct {
	SessionID            []byte   `protobuf:"bytes,1,opt,name=SessionID,proto3" json:"SessionID,omitempty"`
	Index                uint32   `protobuf:"varint,2,opt,name=Index,proto3" json:"Index,omitempty"`
	Status               bool     `protobuf:"varint,3,opt,name=Status,proto3" json:"Status,omitempty"`
	Signature            []byte   `protobuf:"bytes,4,opt,name=Signature,proto3" json:"Signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{2}
}
func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (dst *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(dst, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetSessionID() []byte {
	if m != nil {
		return m.SessionID
	}
	return nil
}

func (m *Response) GetIndex() uint32 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *Response) GetStatus() bool {
	if m != nil {
		return m.Status
	}
	return false
}

func (m *Response) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

type Responses struct {
	Responses            []*Response `protobuf:"bytes,1,rep,name=Responses,proto3" json:"Responses,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Responses) Reset()         { *m = Responses{} }
func (m *Responses) String() string { return proto.CompactTextString(m) }
func (*Responses) ProtoMessage()    {}
func (*Responses) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{3}
}
func (m *Responses) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Responses.Unmarshal(m, b)
}
func (m *Responses) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Responses.Marshal(b, m, deterministic)
}
func (dst *Responses) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Responses.Merge(dst, src)
}
func (m *Responses) XXX_Size() int {
	return xxx_messageInfo_Responses.Size(m)
}
func (m *Responses) XXX_DiscardUnknown() {
	xxx_messageInfo_Responses.DiscardUnknown(m)
}

var xxx_messageInfo_Responses proto.InternalMessageInfo

func (m *Responses) GetResponses() []*Response {
	if m != nil {
		return m.Responses
	}
	return nil
}

type Justification struct {
	SessionID            []byte   `protobuf:"bytes,1,opt,name=SessionID,proto3" json:"SessionID,omitempty"`
	Index                uint32   `protobuf:"varint,2,opt,name=Index,proto3" json:"Index,omitempty"`
	Deal                 []byte   `protobuf:"bytes,3,opt,name=Deal,proto3" json:"Deal,omitempty"`
	Signature            []byte   `protobuf:"bytes,4,opt,name=Signature,proto3" json:"Signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Justification) Reset()         { *m = Justification{} }
func (m *Justification) String() string { return proto.CompactTextString(m) }
func (*Justification) ProtoMessage()    {}
func (*Justification) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{4}
}
func (m *Justification) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Justification.Unmarshal(m, b)
}
func (m *Justification) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Justification.Marshal(b, m, deterministic)
}
func (dst *Justification) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Justification.Merge(dst, src)
}
func (m *Justification) XXX_Size() int {
	return xxx_messageInfo_Justification.Size(m)
}
func (m *Justification) XXX_DiscardUnknown() {
	xxx_messageInfo_Justification.DiscardUnknown(m)
}

var xxx_messageInfo_Justification proto.InternalMessageInfo

func (m *Justification) GetSessionID() []byte {
	if m != nil {
		return m.SessionID
	}
	return nil
}

func (m *Justification) GetIndex() uint32 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *Justification) GetDeal() []byte {
	if m != nil {
		return m.Deal
	}
	return nil
}

func (m *Justification) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

type PublicKey struct {
	PublicKey            []byte   `protobuf:"bytes,1,opt,name=PublicKey,proto3" json:"PublicKey,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PublicKey) Reset()         { *m = PublicKey{} }
func (m *PublicKey) String() string { return proto.CompactTextString(m) }
func (*PublicKey) ProtoMessage()    {}
func (*PublicKey) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{5}
}
func (m *PublicKey) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PublicKey.Unmarshal(m, b)
}
func (m *PublicKey) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PublicKey.Marshal(b, m, deterministic)
}
func (dst *PublicKey) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PublicKey.Merge(dst, src)
}
func (m *PublicKey) XXX_Size() int {
	return xxx_messageInfo_PublicKey.Size(m)
}
func (m *PublicKey) XXX_DiscardUnknown() {
	xxx_messageInfo_PublicKey.DiscardUnknown(m)
}

var xxx_messageInfo_PublicKey proto.InternalMessageInfo

func (m *PublicKey) GetPublicKey() []byte {
	if m != nil {
		return m.PublicKey
	}
	return nil
}

type Signature struct {
	Index                uint32   `protobuf:"varint,1,opt,name=Index,proto3" json:"Index,omitempty"`
	Signature            []byte   `protobuf:"bytes,2,opt,name=Signature,proto3" json:"Signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Signature) Reset()         { *m = Signature{} }
func (m *Signature) String() string { return proto.CompactTextString(m) }
func (*Signature) ProtoMessage()    {}
func (*Signature) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{6}
}
func (m *Signature) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Signature.Unmarshal(m, b)
}
func (m *Signature) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Signature.Marshal(b, m, deterministic)
}
func (dst *Signature) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Signature.Merge(dst, src)
}
func (m *Signature) XXX_Size() int {
	return xxx_messageInfo_Signature.Size(m)
}
func (m *Signature) XXX_DiscardUnknown() {
	xxx_messageInfo_Signature.DiscardUnknown(m)
}

var xxx_messageInfo_Signature proto.InternalMessageInfo

func (m *Signature) GetIndex() uint32 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *Signature) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

type PublicKeys struct {
	PublicKey            [][]byte `protobuf:"bytes,1,rep,name=PublicKey,proto3" json:"PublicKey,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PublicKeys) Reset()         { *m = PublicKeys{} }
func (m *PublicKeys) String() string { return proto.CompactTextString(m) }
func (*PublicKeys) ProtoMessage()    {}
func (*PublicKeys) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{7}
}
func (m *PublicKeys) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PublicKeys.Unmarshal(m, b)
}
func (m *PublicKeys) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PublicKeys.Marshal(b, m, deterministic)
}
func (dst *PublicKeys) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PublicKeys.Merge(dst, src)
}
func (m *PublicKeys) XXX_Size() int {
	return xxx_messageInfo_PublicKeys.Size(m)
}
func (m *PublicKeys) XXX_DiscardUnknown() {
	xxx_messageInfo_PublicKeys.DiscardUnknown(m)
}

var xxx_messageInfo_PublicKeys proto.InternalMessageInfo

func (m *PublicKeys) GetPublicKey() [][]byte {
	if m != nil {
		return m.PublicKey
	}
	return nil
}

func init() {
	proto.RegisterType((*EncryptedDeal)(nil), "internal.EncryptedDeal")
	proto.RegisterType((*EncryptedDeals)(nil), "internal.EncryptedDeals")
	proto.RegisterType((*Response)(nil), "internal.Response")
	proto.RegisterType((*Responses)(nil), "internal.Responses")
	proto.RegisterType((*Justification)(nil), "internal.Justification")
	proto.RegisterType((*PublicKey)(nil), "internal.PublicKey")
	proto.RegisterType((*Signature)(nil), "internal.Signature")
	proto.RegisterType((*PublicKeys)(nil), "internal.PublicKeys")
}

func init() { proto.RegisterFile("msg.proto", fileDescriptor_c06e4cca6c2cc899) }

var fileDescriptor_c06e4cca6c2cc899 = []byte{
	// 307 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x92, 0xc1, 0x4b, 0xfb, 0x30,
	0x14, 0xc7, 0xe9, 0xaf, 0xdd, 0x68, 0xdf, 0xcf, 0x7a, 0x08, 0xa2, 0x3d, 0x78, 0x18, 0x39, 0x4d,
	0xc1, 0x22, 0x7a, 0x96, 0x1d, 0xac, 0xe0, 0x14, 0x44, 0xb2, 0xbf, 0xa0, 0xeb, 0x9e, 0x33, 0x50,
	0x93, 0xda, 0xa4, 0xe0, 0xfe, 0x7b, 0x69, 0x9a, 0xb6, 0xcb, 0x0e, 0x0a, 0xde, 0xf2, 0xfd, 0xe6,
	0x25, 0xdf, 0x4f, 0xf2, 0x1e, 0x44, 0x1f, 0x6a, 0x9b, 0x56, 0xb5, 0xd4, 0x92, 0x84, 0x5c, 0x68,
	0xac, 0x45, 0x5e, 0xd2, 0x4f, 0x88, 0x1f, 0x44, 0x51, 0xef, 0x2a, 0x8d, 0x9b, 0x0c, 0xf3, 0x92,
	0x9c, 0xc0, 0x24, 0x7b, 0x7c, 0xc6, 0x5d, 0xe2, 0xcd, 0xbc, 0xf9, 0x11, 0xeb, 0x04, 0x39, 0x87,
	0x68, 0xc5, 0xb7, 0x22, 0xd7, 0x4d, 0x8d, 0xc9, 0x3f, 0xb3, 0x33, 0x1a, 0xed, 0x99, 0x17, 0x29,
	0x0a, 0x4c, 0xfc, 0xee, 0x8c, 0x11, 0xe4, 0x14, 0xa6, 0xf7, 0xbc, 0x7a, 0xc7, 0x3a, 0x09, 0x8c,
	0x6d, 0x15, 0x5d, 0xc0, 0xb1, 0x13, 0xa9, 0xc8, 0x15, 0x4c, 0xcc, 0x22, 0xf1, 0x66, 0xfe, 0xfc,
	0xff, 0xcd, 0x59, 0xda, 0xe3, 0xa5, 0x4e, 0x21, 0xeb, 0xaa, 0xa8, 0x86, 0x90, 0xa1, 0xaa, 0xa4,
	0x50, 0x68, 0xc0, 0x50, 0x29, 0x2e, 0xc5, 0x32, 0xb3, 0xc8, 0xa3, 0xd1, 0x82, 0x2d, 0xc5, 0x06,
	0xbf, 0x0c, 0x72, 0xcc, 0x3a, 0xd1, 0x82, 0xad, 0x74, 0xae, 0x1b, 0x65, 0x78, 0x43, 0x66, 0x95,
	0xfb, 0xc8, 0xe0, 0xe0, 0x91, 0xf4, 0x0e, 0xa2, 0x3e, 0x55, 0x91, 0xeb, 0x3d, 0x61, 0xa9, 0xc9,
	0x48, 0xdd, 0x6f, 0xb1, 0xb1, 0x88, 0x36, 0x10, 0x3f, 0x35, 0x4a, 0xf3, 0x37, 0x5e, 0xe4, 0x9a,
	0x4b, 0xf1, 0x27, 0x72, 0x02, 0x41, 0xfb, 0x05, 0xf6, 0x9f, 0xcd, 0xfa, 0x17, 0xea, 0x0b, 0x88,
	0x5e, 0x9b, 0x75, 0xc9, 0x0b, 0xdb, 0xc5, 0x41, 0xf4, 0x91, 0x83, 0x41, 0x17, 0xe0, 0xb6, 0xb4,
	0xcb, 0xf7, 0xf6, 0xf3, 0x7f, 0x1c, 0x03, 0x7a, 0x09, 0x30, 0xdc, 0xa6, 0x0e, 0xc3, 0x7c, 0x27,
	0x6c, 0x3d, 0x35, 0x83, 0x78, 0xfb, 0x1d, 0x00, 0x00, 0xff, 0xff, 0xfa, 0x26, 0x86, 0xcc, 0x95,
	0x02, 0x00, 0x00,
}
