version: '3'
services:
 bootstrap:
   image: peernode
   deploy:
     replicas: 1
   environment:
     - NODEROLE=boot
     - PEERSIZE=10
 peernode:
   image: peernode
   depends_on:
     - bootstrap
   deploy:
     replicas: 10
   environment:
     - BOOTSTRAPIP=bootstrap:44460
     - PEERSIZE=10
     - GROUPSIZE=10
     - TESTSTRATEGY=DKG
