version: '3'
services:
 bootstrap:
   image: peernode
   deploy:
     replicas: 1
   environment:
     - APPSESSION=T_DKG
     - APPNAME=BootNode
     - LOGIP=163.172.36.173:9500
     - NODEROLE=boot
     - NODEPORT=44460
     - PEERSIZE=10
     - TESTSTRATEGY=DKG
 peernode:
   image: peernode
   depends_on:
     - bootstrap
   deploy:
     replicas: 10
   environment:
     - APPSESSION=T_DKG
     - APPNAME=PeerNode
     - LOGIP=163.172.36.173:9500
     - BOOTSTRAPIP=bootstrap:44460
     - NODEPORT=44460
     - PEERSIZE=10
     - GROUPSIZE=10
     - TESTSTRATEGY=DKG
