version: '3'
services:
  bootstrap:
    image: peernode
    deploy:
      replicas: 1
    environment:
      - NODEROLE=boot
      - PEERSIZE=5
      - DKGROUND=5
  peernode:
    image: peernode
    depends_on:
      - bootstrap
    deploy:
      replicas: 5
    environment:
      - BOOTSTRAPIP=bootstrap:44460
      - PEERSIZE=5
      - GROUPSIZE=5
      - TESTSTRATEGY=DKGMULTIGROUPING
