version: '3'
services:
 bootstrap:
   image: peernode
   deploy:
     replicas: 1
   environment:
     - appSubject=T_FindNode
     - appName=BootNode
     - NODEROLE=boot
     - PEERSIZE=10
     - NUMOFMESSAGS=1
     - TESTSTRATEGY=FINDNODE
 peernode:
   image: peernode
   depends_on:
     - bootstrap
   deploy:
     replicas: 10
   environment:
     - appSubject=T_FindNode
     - appName=PeerNode
     - BOOTSTRAPIP=bootstrap:44460
     - PEERSIZE=10
     - NUMOFMESSAGS=1
     - TESTSTRATEGY=FINDNODE
