version: '3'
services:
 bootstrap:
   image: peernode
   deploy:
     replicas: 1
   environment:
     - NODEROLE=boot
     - PEERSIZE=20
     - NUMOFMESSAGS=2
 peernode:
   image: peernode
   depends_on:
     - bootstrap
   deploy:
     replicas: 20
   environment:
     - BOOTSTRAPIP=bootstrap:44460
     - PEERSIZE=20
     - NUMOFMESSAGS=2
     - TESTSTRATEGY=FINDNODE
