version: '3'
services:
 bootstrap:
   image: nien0223/dhttest:peernodev1
   deploy:
     replicas: 1
   environment:
     - NODEROLE=boot
     - PEERSIZE=20
     - NUMOFMESSAGS=10
 peernode:
   image: nien0223/dhttest:peernodev1
   depends_on:
     - bootstrap
   deploy:
     replicas: 20
   environment:
     - BOOTSTRAPIP=bootstrap:44460
     - PEERSIZE=20
     - NUMOFMESSAGS=10
     - TESTSTRATEGY=SENDMESSAGE
