version: '3'
services:
 bootstrap:
   image: peernode
   deploy:
     replicas: 1
   environment:
     - APPSESSION=T_Retry
     - APPNAME=BootNode
     - LOGIP=163.172.36.173:9500
     - NODEROLE=boot
     - NODEPORT=44460
     - PEERSIZE=1
     - TESTSTRATEGY=DELAY_BEFORE_RECEIVELOOP
 peernode:
   image: peernode
   depends_on:
     - bootstrap
   deploy:
     replicas: 1
   environment:
     - APPSESSION=T_Retry
     - APPNAME=PeerNode
     - LOGIP=163.172.36.173:9500
     - BOOTSTRAPIP=bootstrap:44460
     - NODEROLE=TESTNODE
     - NODEPORT=44460
     - PEERSIZE=1
     - NUMOFMESSAGS=10
     - TESTSTRATEGY=DELAY_BEFORE_RECEIVELOOP
