version: '3'
services:
  bootstrap:
    image: peernode
    deploy:
      replicas: 1
    environment:
      - appSubject=T_TBLS
      - appName=BootNode
      - NODEROLE=boot
      - PEERSIZE=10
      - TESTSTRATEGY=TBLS
  peernode:
    image: peernode
    depends_on:
      - bootstrap
    deploy:
      replicas: 10
    environment:
      - appSubject=T_TBLS
      - appName=PeerNode
      - BOOTSTRAPIP=bootstrap:44460
      - PEERSIZE=10
      - GROUPSIZE=10
      - TESTSTRATEGY=TBLS
      - URL=https://api.coinbase.com/v2/prices/ETH-USD/spot
