version: '3'
services:
  bootstrap:
    image: peernode
    deploy:
      replicas: 1
    environment:
      - NODEROLE=boot
      - PEERSIZE=3
  peernode:
    image: peernode
    depends_on:
      - bootstrap
    deploy:
      replicas: 3
    environment:
      - BOOTSTRAPIP=bootstrap:44460
      - PEERSIZE=3
      - GROUPSIZE=3
      - TESTSTRATEGY=TBLS
      - URL=https://api.coinbase.com/v2/prices/ETH-USD/spot