// Code generated by protoc-gen-go. DO NOT EDIT.
// source: msg.proto

package internalMsg

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Cmd_Type int32

const (
	Cmd_CHECKURL Cmd_Type = 0
)

var Cmd_Type_name = map[int32]string{
	0: "CHECKURL",
}

var Cmd_Type_value = map[string]int32{
	"CHECKURL": 0,
}

func (x Cmd_Type) String() string {
	return proto.EnumName(Cmd_Type_name, int32(x))
}

func (Cmd_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{0, 0}
}

type Cmd struct {
	Ctype                Cmd_Type `protobuf:"varint,1,opt,name=Ctype,proto3,enum=internalMsg.Cmd_Type" json:"Ctype,omitempty"`
	Args                 string   `protobuf:"bytes,2,opt,name=Args,proto3" json:"Args,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Cmd) Reset()         { *m = Cmd{} }
func (m *Cmd) String() string { return proto.CompactTextString(m) }
func (*Cmd) ProtoMessage()    {}
func (*Cmd) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{0}
}
func (m *Cmd) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Cmd.Unmarshal(m, b)
}
func (m *Cmd) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Cmd.Marshal(b, m, deterministic)
}
func (dst *Cmd) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Cmd.Merge(dst, src)
}
func (m *Cmd) XXX_Size() int {
	return xxx_messageInfo_Cmd.Size(m)
}
func (m *Cmd) XXX_DiscardUnknown() {
	xxx_messageInfo_Cmd.DiscardUnknown(m)
}

var xxx_messageInfo_Cmd proto.InternalMessageInfo

func (m *Cmd) GetCtype() Cmd_Type {
	if m != nil {
		return m.Ctype
	}
	return Cmd_CHECKURL
}

func (m *Cmd) GetArgs() string {
	if m != nil {
		return m.Args
	}
	return ""
}

func init() {
	proto.RegisterType((*Cmd)(nil), "internalMsg.Cmd")
	proto.RegisterEnum("internalMsg.Cmd_Type", Cmd_Type_name, Cmd_Type_value)
}

func init() { proto.RegisterFile("msg.proto", fileDescriptor_c06e4cca6c2cc899) }

var fileDescriptor_c06e4cca6c2cc899 = []byte{
	// 129 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xcc, 0x2d, 0x4e, 0xd7,
	0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0xce, 0xcc, 0x2b, 0x49, 0x2d, 0xca, 0x4b, 0xcc, 0xf1,
	0x2d, 0x4e, 0x57, 0x8a, 0xe1, 0x62, 0x76, 0xce, 0x4d, 0x11, 0xd2, 0xe6, 0x62, 0x75, 0x2e, 0xa9,
	0x2c, 0x48, 0x95, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x33, 0x12, 0xd5, 0x43, 0x52, 0xa3, 0xe7, 0x9c,
	0x9b, 0xa2, 0x17, 0x52, 0x59, 0x90, 0x1a, 0x04, 0x51, 0x23, 0x24, 0xc4, 0xc5, 0xe2, 0x58, 0x94,
	0x5e, 0x2c, 0xc1, 0xa4, 0xc0, 0xa8, 0xc1, 0x19, 0x04, 0x66, 0x2b, 0x89, 0x70, 0xb1, 0x80, 0x94,
	0x08, 0xf1, 0x70, 0x71, 0x38, 0x7b, 0xb8, 0x3a, 0x7b, 0x87, 0x06, 0xf9, 0x08, 0x30, 0x24, 0xb1,
	0x81, 0x6d, 0x34, 0x06, 0x04, 0x00, 0x00, 0xff, 0xff, 0xb0, 0xd4, 0xa1, 0x13, 0x7e, 0x00, 0x00,
	0x00,
}
